added certbot dns cloudflare validation function

diff --git a/web/rootfs/etc/cont-init.d/10-config b/web/rootfs/etc/cont-init.d/10-config
--- a/web/rootfs/etc/cont-init.d/10-config
+++ b/web/rootfs/etc/cont-init.d/10-config
@@ -11,7 +11,35 @@ mkdir -p \
 if [[ $DISABLE_HTTPS -ne 1 ]]; then
     if [[ $ENABLE_LETSENCRYPT -eq 1 ]]; then
         if [[ ! -f /etc/letsencrypt/live/$LETSENCRYPT_DOMAIN/fullchain.pem ]]; then
-            if ! certbot-auto \
+           if [[ $ENABLE_DNS_CLOUDFLARE -eq 1 ]]; then
+              # check if dns clouflare credential file is exist
+              if [[ ! -f /etc/dns-cloudflare.txt ]]; then
+		        echo "dns_cloudflare_email = $DNS_CLOUDFLARE_EMAIL" >> /etc/.dns-cloudflare.txt
+		        echo "dns_cloudflare_api_key = $DNS_CLOUDFLARE_API_KEY" >> /etc/.dns-cloudflare.txt
+                chmod 400 /etc/.dns-cloudflare.txt
+              fi
+              
+              # generate the certificate
+              if ! certbot-auto \
+                  certonly \
+                  --no-self-upgrade \
+                  --noninteractive \
+                  --dns-cloudflare \
+                  --dns-cloudflare-credentialss /etc/.dns-cloudflare.txt \
+                  --dns-cloudflare-propagation-seconds 60 \
+                  -d $LETSENCRYPT_DOMAIN \
+                  --agree-tos \
+                  --email $LETSENCRYPT_EMAIL ; then
+
+                echo "Failed to obtain a certificate from the Let's Encrypt CA."
+                # this tries to get the user's attention and to spare the
+                # authority's rate limit:
+                sleep 15
+                echo "Exiting."
+                exit 1
+             fi
+           else
+             if ! certbot-auto \
                   certonly \
                   --no-self-upgrade \
                   --noninteractive \
@@ -29,7 +57,7 @@ if [[ $DISABLE_HTTPS -ne 1 ]]; then
                 exit 1
             fi
         fi
-
+        
         # remove default certbot renewal
         if [[ -f /etc/cron.d/certbot ]]; then
             rm /etc/cron.d/certbot
